### PR TITLE
Adding jenniferlucia.com to site list, cleaning up some spaces/cruft

### PR DESCRIPTION
**Pull request by dajeffers**
Title says all.

### CODE REVIEW

**Comment by dajeffers** [comment]
Wow, that was quicker than I anticipated. I will have the image up soon, it's invalid currently. I figured I'd have a bit of time to get away with it.

**Comment by konaraddio** [comment]
No worries, thanks for letting me know

**Comment by dajeffers** [comment]
You're welcome, if you need the image sooner, it IS mirrored at http://dsjsystems.com/images/jenniferlucia_com_bulma.png. I just wanted to provide an https link and one from the server hosting the site itself.

**Comment by konaraddio** [comment]
That'll do, I'll use that link

**Pull request merged**
